name: LeetCode Golang Tester

trigger:
- main

pool: self-hosted agents


stages:
- stage: run_tests
  jobs:
    - job: 
      container: golang:latest
      steps:
      - bash: go version
        displayName: Display Go Version
      - bash: go test -v ./...
        displayName: Run Tests
      displayName: Run test cases