name: LeetCode Golang Tester

trigger:
- main

pool:
  name: self-hosted agents
  demands:
    - docker
    - agent.os -equals Linux

stages:
- stage: run_tests
  displayName: Run go tests
  jobs:
    - job: 
      steps:
      - bash: make test
        displayName: Run Tests

- stage: run_coverage
  displayName: Display test coverage
  dependsOn: []
  jobs:
  - job:
    steps:
    - bash: make cover
      displayName: Generate Coverage

- stage: run_linter
  displayName: Lint code
  dependsOn: []
  jobs:
  - job: 
    steps:
    - bash: make lint
    displayName: Run linter

