# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: self-hosted agents

steps:
- bash: go version
  displayName: Display Go Version
- bash: go test -v ./...
  displayName: Run Tests
