name: LeetCode Golang Tester

trigger:
- main

pool:
  name: self-hosted agents
  demands:
    - docker
    - agent.os -equals Linux


stages:
- stage: run_tests
  jobs:
    - job: 
      container: golang:latest
      steps:
      - bash: go version
        displayName: Display Go Version
      - bash: go test -v ./...
        displayName: Run Tests
      displayName: Run test cases

- stage: publish_test_coverage
  dependsOn: []
  jobs:
    - job: 
      container: golang:latest
      steps:
        - bash: go tool cover -func=coverage.out
          displayName: Get test coverage
      displayName: Display test coverage